[2023-06-26T01:48:03.483+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-06-25T00:00:00+00:00 [queued]>
[2023-06-26T01:48:03.571+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-06-25T00:00:00+00:00 [queued]>
[2023-06-26T01:48:03.573+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-26T01:48:03.928+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): inaccurate> on 2023-06-25 00:00:00+00:00
[2023-06-26T01:48:04.003+0000] {standard_task_runner.py:57} INFO - Started process 241 to run task
[2023-06-26T01:48:04.135+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2023-06-25T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpzm6b1ipx']
[2023-06-26T01:48:04.269+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask inaccurate
[2023-06-26T01:48:06.580+0000] {task_command.py:410} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2023-06-25T00:00:00+00:00 [running]> on host 414be138234a
[2023-06-26T01:48:16.318+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-25T00:00:00+00:00'
[2023-06-26T01:48:16.399+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-06-26T01:48:16.441+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo inaccurate']
[2023-06-26T01:48:18.465+0000] {subprocess.py:86} INFO - Output:
[2023-06-26T01:48:19.013+0000] {subprocess.py:93} INFO - inaccurate
[2023-06-26T01:48:19.104+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-26T01:48:21.868+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20230625T000000, start_date=20230626T014803, end_date=20230626T014821
[2023-06-26T01:48:22.739+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-26T01:48:24.832+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
