[2023-06-27T01:45:20.661+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: search_posts.get_posts manual__2023-06-27T01:45:11.848109+00:00 [queued]>
[2023-06-27T01:45:20.806+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: search_posts.get_posts manual__2023-06-27T01:45:11.848109+00:00 [queued]>
[2023-06-27T01:45:20.815+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T01:45:21.052+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_posts> on 2023-06-27 01:45:11.848109+00:00
[2023-06-27T01:45:21.140+0000] {standard_task_runner.py:57} INFO - Started process 203 to run task
[2023-06-27T01:45:21.275+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'search_posts', 'get_posts', 'manual__2023-06-27T01:45:11.848109+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/search_posts.py', '--cfg-path', '/tmp/tmpn3xsrr08']
[2023-06-27T01:45:21.327+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask get_posts
[2023-06-27T01:45:25.207+0000] {task_command.py:410} INFO - Running <TaskInstance: search_posts.get_posts manual__2023-06-27T01:45:11.848109+00:00 [running]> on host 414be138234a
[2023-06-27T01:45:28.028+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='search_posts' AIRFLOW_CTX_TASK_ID='get_posts' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T01:45:11.848109+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T01:45:11.848109+00:00'
[2023-06-27T01:45:28.047+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/search_posts.py", line 27, in get_posts
    reddit.connect_reddit(pickle_name = 'monkey')
  File "/opt/airflow/dags/lib/reddit_api.py", line 41, in connect_reddit
    self.your_pickle = pickle.load(open(pickle_name+'.pkl','rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'monkey.pkl'
[2023-06-27T01:45:29.080+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=search_posts, task_id=get_posts, execution_date=20230627T014511, start_date=20230627T014520, end_date=20230627T014529
[2023-06-27T01:45:31.118+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 68 for task get_posts ([Errno 2] No such file or directory: 'monkey.pkl'; 203)
[2023-06-27T01:45:31.576+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-27T01:45:31.971+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
